# Generated by Django 3.2.21 on 2023-11-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=100)),
                ('udp_stream', models.URLField()),
                ('video_codec', models.CharField(max_length=100)),
                ('audio_codec', models.CharField(max_length=100)),
                ('preset', models.CharField(max_length=100)),
                ('video_bitrate', models.IntegerField()),
                ('resolution', models.CharField(max_length=100)),
                ('field_for_future_changes', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
