# Generated by Django 3.2.21 on 2023-11-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_field_for_future_changes_channels_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='udp_stream',
            field=models.CharField(max_length=100),
        ),
    ]
