# Generated by Django 3.2.21 on 2023-11-04 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_url_channels_output_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channels',
            old_name='udp_stream',
            new_name='stream',
        ),
    ]
